server:
  port: 8080
  address: 0.0.0.0
workers:
  urls:
    - http://crackhash-worker-1:8080
    - http://crackhash-worker-2:8080
    - http://crackhash-worker-3:8080
    - http://crackhash-worker-4:8080
    - http://crackhash-worker-5:8080
    - http://crackhash-worker-6:8080
    - http://crackhash-worker-7:8080
    - http://crackhash-worker-8:8080

spring:
  amqp:
    deserialization:
      trust:
        all: true
  data:
    mongodb:
      uri: mongodb://${MONGO_DEFAULT_HOST1:localhost},${MONGO_DEFAULT_HOST2:localhost},${MONGO_DEFAULT_HOST3:localhost}:${MONGO_DEFAULT_PORT:27017}/crackhash?replicaSet=myReplicaSet&readPreference=primaryPreferred

  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:localhost}
    port: ${RABBITMQ_DEFAULT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASSWORD:guest}

queue:
  task_request: task_request
  task_response: task_response
  dlq: dlq_queue

exchange:
  tasks: task_exchange
  dlx: dlx_exchange

routing:
  task_request: task_request_key
  task_response: task_response_key
  dlq: dlq_routing_key

workers_num: ${WORKERS:1}

